# Generated by Django 4.1.4 on 2022-12-10 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('vendors', '0001_initial'),
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('status', models.CharField(max_length=255)),
                ('borrow_date', models.DateField(default=None, null=True)),
                ('return_date', models.DateField(default=None, null=True)),
                ('charge', models.DecimalField(decimal_places=4, max_digits=6)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('borrower', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libraries.library')),
                ('publisher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
